package DayFive;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class DayFive {

    private static final int allRows = 127;

    private static List<Integer> allSeats = new ArrayList<Integer>();

    public int partOne(String input) {
        int maxValue = Integer.MIN_VALUE;
        for(String s : input.split("\n")) {
            int row = binarySearch(s.substring(0, 7), 127);
            int column = binarySearch(s.substring(7, 10), 7);
            int seatValue = (row * 8) + column;
            if(seatValue > maxValue) {
                maxValue = seatValue;
            }
            allSeats.add(seatValue);
        }
        return maxValue;
    }

    public int partTwo() {
        Collections.sort(allSeats);

        int mySeat = Integer.MIN_VALUE;
        int minimumSeatValue = allSeats.get(0);
        for(int i = 1; i < allSeats.size(); i++) {
            int nextSeatValue = allSeats.get(i);
            if(nextSeatValue != minimumSeatValue + 1) {
                return minimumSeatValue + 1;
            }
            minimumSeatValue = nextSeatValue;
        }
        return mySeat;
    }

    private int binarySearch(String data, int range) {
        int minRange = 0;
        Collections.sort(allSeats);
        for (String s : data.split("")) {
            int diff = range - minRange;
            if (s.equals("F") || s.equals("L")) {
                range -= Math.ceil(diff / 2.0);
            } else if (s.equals("B") || s.equals("R")) {
                minRange += diff / 2;
            }
        }
        return range;
    }

    public static void main(String[] args) {
        DayFive dayFive = new DayFive();
        System.out.printf("Part one: %d\n", dayFive.partOne(input));
        System.out.printf("Part two: %d", dayFive.partTwo());
    }

    private static final String input = "BFBBBFBLRR\n" +
                                        "BBFFFFFLRR\n" +
                                        "BFBFBFFRLR\n" +
                                        "FBBBBFFLLL\n" +
                                        "BFBBBBFRRL\n" +
                                        "FFBFFBFRLR\n" +
                                        "FFFBFBBRRL\n" +
                                        "FBFBBFBLRL\n" +
                                        "FBFFFBFLLR\n" +
                                        "FFBBFBBLLL\n" +
                                        "FBFBBFFRLL\n" +
                                        "FFBFFBFLRL\n" +
                                        "FFBFBFFRRR\n" +
                                        "BFFFFBBLRR\n" +
                                        "FFBFFBFRRL\n" +
                                        "FFBFBFFLRL\n" +
                                        "BBFFFFFRLL\n" +
                                        "FFFBFBBRRR\n" +
                                        "FBFBFBBLLR\n" +
                                        "FBFBFBFLLR\n" +
                                        "BFBFBFFRLL\n" +
                                        "FFFBFFBRLL\n" +
                                        "BBFFFBFLRL\n" +
                                        "BFBFBFBLLR\n" +
                                        "FFFFBBBRLL\n" +
                                        "FFBBBFFLRL\n" +
                                        "FBFFBFBRLR\n" +
                                        "FFBFBBFLLR\n" +
                                        "FBFBFFFRRL\n" +
                                        "BFBBFBBLRR\n" +
                                        "BFBFFFBRRR\n" +
                                        "BFFBBBFRLL\n" +
                                        "FFBFFFFRRL\n" +
                                        "FFFFBBFLRL\n" +
                                        "BBFFFBBRLR\n" +
                                        "BFFBFBBRRL\n" +
                                        "BFFFFFBLRR\n" +
                                        "FBFFFFBLLL\n" +
                                        "FFBFBBFLLL\n" +
                                        "BFBBBFBRRR\n" +
                                        "BBFFFBFLLR\n" +
                                        "FBBBFFFRRL\n" +
                                        "BFBBBBBLLL\n" +
                                        "BFBFFFBRLR\n" +
                                        "FFBBFBBLRR\n" +
                                        "FBFBFFFLLL\n" +
                                        "BFBBBFBRLL\n" +
                                        "BFFBFBFRRL\n" +
                                        "BFBFBFFRRR\n" +
                                        "FBBFFFFLLR\n" +
                                        "FFBBBFFLLL\n" +
                                        "BFFBFBBRRR\n" +
                                        "FFBFBFBRRR\n" +
                                        "FFFBBFFRRR\n" +
                                        "FFBBFBFRLR\n" +
                                        "FBBBFBFRRR\n" +
                                        "FFBFFBFRLL\n" +
                                        "BFBBBFFRLR\n" +
                                        "FBFFFFFRLR\n" +
                                        "BFBBBFBRRL\n" +
                                        "FBFFBFBRRL\n" +
                                        "FFBFBBFRLL\n" +
                                        "FFFBBBBLLL\n" +
                                        "FFBBBFBLLR\n" +
                                        "FFBBFFBRRR\n" +
                                        "FFBBBBFRRR\n" +
                                        "FFBFBBBLRL\n" +
                                        "FBBBBBFLLR\n" +
                                        "BFBFBBFLLR\n" +
                                        "FFFBBBFRLL\n" +
                                        "BFBFFBBRRL\n" +
                                        "FBFBBFBLLL\n" +
                                        "FBFFBBFLRR\n" +
                                        "FBBBFBFLRL\n" +
                                        "FFBBFBFRLL\n" +
                                        "FFBBBFFRRR\n" +
                                        "BFFBBBBRLR\n" +
                                        "FFBFFBBRLL\n" +
                                        "FBFBFBBRRL\n" +
                                        "FFBFFBFLLR\n" +
                                        "FBFBFFBLLR\n" +
                                        "FBFBBFFLLL\n" +
                                        "FBFBBFBLLR\n" +
                                        "FBBFBBFRLL\n" +
                                        "BFFFBFFRLL\n" +
                                        "FFBBBFFRLL\n" +
                                        "FBFBBFBRRR\n" +
                                        "BFFBBFFRLL\n" +
                                        "FFBFBBFRRR\n" +
                                        "FBBFFFFRRL\n" +
                                        "BFBBFBFLRR\n" +
                                        "BFBFFFFLRL\n" +
                                        "BFFFFBBRRR\n" +
                                        "BFFBFFBLRR\n" +
                                        "FBFFFBFLRL\n" +
                                        "FBFBFBFLRL\n" +
                                        "FFBBFBFRRR\n" +
                                        "BFFFFBFRRR\n" +
                                        "FBBBBBFLRL\n" +
                                        "BFFFBBBRLL\n" +
                                        "BFFBBBBLRR\n" +
                                        "FFBBBBFRLR\n" +
                                        "BFFFBBFRLR\n" +
                                        "FBBFFBFLLR\n" +
                                        "FBFBBBFLRR\n" +
                                        "FBFFFFBRRR\n" +
                                        "FFBBBBBLLR\n" +
                                        "FFBBFFFRRL\n" +
                                        "FBBFFBBLRL\n" +
                                        "FBFBBBFRRL\n" +
                                        "BFFBFBFRRR\n" +
                                        "FFBBBBFLLR\n" +
                                        "FFBBFFBLRL\n" +
                                        "FFBBBBBRLL\n" +
                                        "FFFBFBBLRL\n" +
                                        "BFFFBFFLRR\n" +
                                        "BFBBBFFLRR\n" +
                                        "FFBFFFFRRR\n" +
                                        "FBBFFBBLLR\n" +
                                        "FBBBBFFRRR\n" +
                                        "BFBBBFFRRL\n" +
                                        "FBBFFBBLLL\n" +
                                        "FBFBFBBLRL\n" +
                                        "BFBBBFFLLR\n" +
                                        "BBFFFBBLRL\n" +
                                        "FBBBFBBLLR\n" +
                                        "BBFFBFFLLL\n" +
                                        "FBBBFFFRRR\n" +
                                        "BFFBBFFLRR\n" +
                                        "FFBBFFFRLL\n" +
                                        "BFBBFFFLRR\n" +
                                        "FFBFFFFLLR\n" +
                                        "FFFBFFBLLL\n" +
                                        "FFBBBFFRLR\n" +
                                        "FFBFFFBRRR\n" +
                                        "FBFBBBBLRL\n" +
                                        "FBBFBBBRLL\n" +
                                        "FBBFBFFLLR\n" +
                                        "FFFFBFBLRR\n" +
                                        "BFFFBBFLRL\n" +
                                        "FBFFBBFRLR\n" +
                                        "BBFFFFBRRR\n" +
                                        "FFFBBBFLRL\n" +
                                        "FBBFBFFRRR\n" +
                                        "BFFBBFBRRR\n" +
                                        "FFFFBBBRLR\n" +
                                        "FBBBFBBRLL\n" +
                                        "FBBFBFFRRL\n" +
                                        "FBFFFFBLRR\n" +
                                        "BFFBBBBLRL\n" +
                                        "FBBBBBFRLR\n" +
                                        "FFFBFFBLLR\n" +
                                        "FBBFBFBRLR\n" +
                                        "FBBBBBFRRR\n" +
                                        "BFBBFFBRLR\n" +
                                        "BFFFFFBRRR\n" +
                                        "FFFBFFBRRR\n" +
                                        "BFBBBBFLLL\n" +
                                        "BFBFFFFLRR\n" +
                                        "FFBBFBBRRR\n" +
                                        "BBFFFBFRLL\n" +
                                        "FFBBBBBLRR\n" +
                                        "FBBBFBFLLR\n" +
                                        "FBFFFFFRLL\n" +
                                        "FFBBFFBLRR\n" +
                                        "FBFFFFFLRR\n" +
                                        "BFBBFBFRRR\n" +
                                        "FFBBFFBRLR\n" +
                                        "FBBFFFBLLL\n" +
                                        "BFFBFBFLLR\n" +
                                        "FBBFBFFRLL\n" +
                                        "FBBBBFBLRL\n" +
                                        "BFFFFBFRRL\n" +
                                        "FBFBBFBRRL\n" +
                                        "BFFFFBBLLL\n" +
                                        "FBFFBFBLLR\n" +
                                        "BFFBBFBRLL\n" +
                                        "BFBFFFBRRL\n" +
                                        "FBFFBFFLLR\n" +
                                        "BFBFFFFRRL\n" +
                                        "FFBFFFBRLR\n" +
                                        "FFBBBBFLRR\n" +
                                        "BBFFFFBLLL\n" +
                                        "BFBBBBBRLL\n" +
                                        "FFBFBBFRLR\n" +
                                        "BBFFFFFRLR\n" +
                                        "FBFFFBBRRR\n" +
                                        "BFFFBFBRLL\n" +
                                        "FBBBBFFLRL\n" +
                                        "BFFFFBFLRR\n" +
                                        "FBBFBFFLRL\n" +
                                        "BFBFBFBLRL\n" +
                                        "FBBFFBFRLR\n" +
                                        "FBBFFFBLLR\n" +
                                        "FBBBBFFRLL\n" +
                                        "BFBBBFFRRR\n" +
                                        "FBBFBBFLLR\n" +
                                        "FBBFFBFLRL\n" +
                                        "BFFBFBBLLR\n" +
                                        "FBBBFBFLLL\n" +
                                        "FBBBBBBRRR\n" +
                                        "FBFBBFBRLR\n" +
                                        "FFBFBFBRRL\n" +
                                        "FBFBBBBRRR\n" +
                                        "FFBBBFBLRR\n" +
                                        "FBFFBFBLRL\n" +
                                        "FFBFFFBLRL\n" +
                                        "BFBFBFFLRR\n" +
                                        "FBFFFFBLRL\n" +
                                        "BFFBFFFLRR\n" +
                                        "BFBBBBFRLL\n" +
                                        "FBFFBBBLRL\n" +
                                        "FBFBFBBLRR\n" +
                                        "BFBFFFBLRL\n" +
                                        "BFBFBBBLRL\n" +
                                        "FFBFBFBLRL\n" +
                                        "BFFBFFBRRL\n" +
                                        "BBFFFBFRRR\n" +
                                        "FFFBFFFRLR\n" +
                                        "FFFBFBFRRL\n" +
                                        "FFBBBFFLRR\n" +
                                        "BFBBBFFRLL\n" +
                                        "BFBBFBBLLL\n" +
                                        "FBBBBFBLLL\n" +
                                        "BFFFBFFRLR\n" +
                                        "BFFBBFBLLL\n" +
                                        "FFBBFBFLLL\n" +
                                        "FFFBFBFLLR\n" +
                                        "FBFFBFFLRR\n" +
                                        "BFBFFBFRLR\n" +
                                        "BFFBBBFLLL\n" +
                                        "FFBFFFBLLL\n" +
                                        "FFFBFFFRRL\n" +
                                        "FFBFFFBLRR\n" +
                                        "FBBFBBFRRR\n" +
                                        "BBFFFBBLLR\n" +
                                        "BFFFBFFLLR\n" +
                                        "FFBFBBBRLL\n" +
                                        "BFFFBBBLRR\n" +
                                        "FFBFBFFLLL\n" +
                                        "FFBFFBBLLL\n" +
                                        "BFBBFBBRRL\n" +
                                        "BBFFFFFRRL\n" +
                                        "FBFFBFFLLL\n" +
                                        "FFBFFBFLRR\n" +
                                        "BBFFFFFRRR\n" +
                                        "FBBFFFBRRL\n" +
                                        "FBFFBBFLRL\n" +
                                        "BFFBBBFRRL\n" +
                                        "BFBBFFFRRL\n" +
                                        "BFBFFBFLRR\n" +
                                        "FBBBFFFLLR\n" +
                                        "FFFFBBBLLR\n" +
                                        "BFFBFFBLRL\n" +
                                        "FFBFFFBLLR\n" +
                                        "FFFBFBBRLL\n" +
                                        "FBFBBBFLLL\n" +
                                        "BFBFBFBRRL\n" +
                                        "BFFFBBBRRL\n" +
                                        "FFFFBBFRRR\n" +
                                        "FBBFBBBLRL\n" +
                                        "FFBBBBBLLL\n" +
                                        "BBFFBFFLLR\n" +
                                        "FBFFBBBLLR\n" +
                                        "BFBFFBFRLL\n" +
                                        "BFFFFFBLRL\n" +
                                        "FFFFBFBLLL\n" +
                                        "FBBBBFBRRL\n" +
                                        "FBFBFFBLRR\n" +
                                        "FFFBBFFLLR\n" +
                                        "FBFBFBFLRR\n" +
                                        "BBFFFBBLRR\n" +
                                        "FFFBBFBLLR\n" +
                                        "FFBBBFBRRR\n" +
                                        "FFFBBBFRRR\n" +
                                        "BFBFBFFLLL\n" +
                                        "FBBBBBFRRL\n" +
                                        "BFFBFFBLLR\n" +
                                        "FFBFBBFLRR\n" +
                                        "BFFBFBBLRR\n" +
                                        "FBBBFBBLRL\n" +
                                        "FBFFBBFRLL\n" +
                                        "BFFBBBBRRL\n" +
                                        "BFFBBBBRRR\n" +
                                        "BFFFBBFRLL\n" +
                                        "BFBBBBBLRR\n" +
                                        "FFBBBBFLRL\n" +
                                        "FBBBBFFLRR\n" +
                                        "BFBFFBBRLR\n" +
                                        "FBBFBBBLRR\n" +
                                        "FBFBFBBRRR\n" +
                                        "BBFFFBBRLL\n" +
                                        "FBBBBFBRLL\n" +
                                        "FFBFBFFLLR\n" +
                                        "FBFFFBFRRR\n" +
                                        "BFBFBBFRRR\n" +
                                        "BFFFBFFRRL\n" +
                                        "BFBFFBFLLR\n" +
                                        "FFFBBBBLLR\n" +
                                        "FBBBFFFLRL\n" +
                                        "FBBFBBFRRL\n" +
                                        "FBBFBBBLLR\n" +
                                        "BFFFFBBLLR\n" +
                                        "FBBBBBBLLL\n" +
                                        "BFFFFFFRRR\n" +
                                        "FFFBBBBRLR\n" +
                                        "FFFBFBFRLR\n" +
                                        "FFFFBFBLRL\n" +
                                        "FBFBFFBRRR\n" +
                                        "FBBBBBBLRR\n" +
                                        "BFBBBFBRLR\n" +
                                        "FBFBBBFRLL\n" +
                                        "FBBFFBBLRR\n" +
                                        "BFFFBBFRRL\n" +
                                        "FBBBBFFRLR\n" +
                                        "BFFBFFBRRR\n" +
                                        "BFFFBFBLLR\n" +
                                        "BFFFBBBRRR\n" +
                                        "BFFBBBFLRL\n" +
                                        "BFBBFBBLRL\n" +
                                        "BFFBBFFLLR\n" +
                                        "BFFFFFBRLR\n" +
                                        "FBBFFBBRRL\n" +
                                        "BFFFFFBRRL\n" +
                                        "FBBBFFBLRL\n" +
                                        "FBFBBFBRLL\n" +
                                        "BFFBFBFLLL\n" +
                                        "BFFBFBBRLR\n" +
                                        "BFFBFFFLRL\n" +
                                        "BFBFBBBLLR\n" +
                                        "FBFBFFBRLL\n" +
                                        "BFFBBFBLLR\n" +
                                        "BFFBFBBLLL\n" +
                                        "BFFBBFBLRL\n" +
                                        "FBBFFBFRRL\n" +
                                        "BFBFBBFRLR\n" +
                                        "FBFFFFBRRL\n" +
                                        "FBFBFFFRRR\n" +
                                        "FFFBBFFRRL\n" +
                                        "FFFFBFBRRL\n" +
                                        "BFFFFFFLLR\n" +
                                        "FBBFFFFRLR\n" +
                                        "FBFBBFFRLR\n" +
                                        "FFBBFFBRRL\n" +
                                        "FBBFBBFRLR\n" +
                                        "FFBBFBFLRL\n" +
                                        "FFFFBBBLLL\n" +
                                        "FFBBFFFLLR\n" +
                                        "BFBBFBBRLL\n" +
                                        "BFFFFBBRRL\n" +
                                        "BFFBBFBRRL\n" +
                                        "FBBFBBBRRL\n" +
                                        "BFBFBFFLRL\n" +
                                        "FBFFFBBLRL\n" +
                                        "FFFFBBBRRR\n" +
                                        "FBFFBBFLLR\n" +
                                        "BFFBBFBRLR\n" +
                                        "FBBFBBFLRL\n" +
                                        "FFBBFFFRLR\n" +
                                        "BBFFFBBRRR\n" +
                                        "FFBBBBBLRL\n" +
                                        "FBBBBBBRLL\n" +
                                        "FFFBBBFRLR\n" +
                                        "FFBBFBFRRL\n" +
                                        "FFBBBBBRRL\n" +
                                        "BFBFBBFRLL\n" +
                                        "FBFFBFFRLR\n" +
                                        "BFBFBBBRLR\n" +
                                        "FFBFFFFLRL\n" +
                                        "FBFFBFBLRR\n" +
                                        "FBFFBFBRRR\n" +
                                        "FFFBBFBRRR\n" +
                                        "FBFFFBFLLL\n" +
                                        "BFFBFBFRLL\n" +
                                        "FBFFBFBRLL\n" +
                                        "FFBFFBBLRR\n" +
                                        "FFFFBFBRLR\n" +
                                        "BFFBBBBRLL\n" +
                                        "BFBBFFBLRR\n" +
                                        "FFBFFBFLLL\n" +
                                        "FFBFBBBRLR\n" +
                                        "FFBFFFFRLR\n" +
                                        "FBBFFFBRLR\n" +
                                        "BFFFFFFLLL\n" +
                                        "BFBBBFFLRL\n" +
                                        "FBBFBFFLLL\n" +
                                        "BFBBFBBRRR\n" +
                                        "BFBFFBBRLL\n" +
                                        "FBBFBFBLRL\n" +
                                        "BBFFFFFLLL\n" +
                                        "FBFFFBFRRL\n" +
                                        "BFBBBFBLLR\n" +
                                        "BFFFFBBRLL\n" +
                                        "FFBFBBFLRL\n" +
                                        "FFFBFBBLLR\n" +
                                        "FBFBFFFLRR\n" +
                                        "FBBBBBBLLR\n" +
                                        "BFFBFFBRLL\n" +
                                        "FBFFBFFRRL\n" +
                                        "FFBFBBBLLR\n" +
                                        "FBBBFBFLRR\n" +
                                        "FFBFBBBRRL\n" +
                                        "FBBFFBBRLR\n" +
                                        "BFFFBBBLRL\n" +
                                        "FBBFBBBRRR\n" +
                                        "BFFBBBFLRR\n" +
                                        "FBBFFFBRRR\n" +
                                        "BFBFFFFRLL\n" +
                                        "BFBBBBBRRR\n" +
                                        "FBFBBFFRRR\n" +
                                        "FBBBBBFLRR\n" +
                                        "FBBBFFBLRR\n" +
                                        "FFBBBBBRRR\n" +
                                        "FFFBFFFLLR\n" +
                                        "BFBBBBFRRR\n" +
                                        "BFFBFBFLRR\n" +
                                        "BFFFBBFLLR\n" +
                                        "FBFFFFFLLL\n" +
                                        "FBBFFFFRLL\n" +
                                        "BFFBBBFRLR\n" +
                                        "BBFFFFBLLR\n" +
                                        "FBBBBFFLLR\n" +
                                        "BFFFBFBRLR\n" +
                                        "BBFFFFFLRL\n" +
                                        "BFFFFBFLRL\n" +
                                        "BFFFFBBLRL\n" +
                                        "FBFFBBBLRR\n" +
                                        "FBFFBBBRRR\n" +
                                        "FBFBBFBLRR\n" +
                                        "FBBBBBBRRL\n" +
                                        "FFFBFFBLRL\n" +
                                        "FBFBFBFRLR\n" +
                                        "FFFBBFBLRR\n" +
                                        "BFBFFBFLRL\n" +
                                        "BFBFFFBRLL\n" +
                                        "BFFFBFBRRR\n" +
                                        "FBFBBBFLLR\n" +
                                        "BFFBBBFRRR\n" +
                                        "BFBFBBFLRR\n" +
                                        "FBBFBFBLLL\n" +
                                        "FBFBBBFRRR\n" +
                                        "BFBBBBFRLR\n" +
                                        "FFFBBBBLRL\n" +
                                        "FFFBFFFLLL\n" +
                                        "FFFBBBFLLL\n" +
                                        "BFBBFFBRRL\n" +
                                        "BFBBFBBLLR\n" +
                                        "FFBBBBFRLL\n" +
                                        "FBBBBFFRRL\n" +
                                        "FFBBBFBRRL\n" +
                                        "FBBFFFBLRL\n" +
                                        "FFBFFBBRLR\n" +
                                        "BFBFFBBLLL\n" +
                                        "FBFFFBFLRR\n" +
                                        "FFBBFFBLLL\n" +
                                        "BFFFFBFLLR\n" +
                                        "FFFBFBFLRL\n" +
                                        "FFFBBBBRLL\n" +
                                        "BBFFFBBRRL\n" +
                                        "BFBFFBBLRR\n" +
                                        "FFFFBFBLLR\n" +
                                        "BFBBFBFLLR\n" +
                                        "BFBBFBFRRL\n" +
                                        "FFBBFBBLLR\n" +
                                        "FBFFBBFRRL\n" +
                                        "BFFBBFFRRL\n" +
                                        "FBFBBBBLLR\n" +
                                        "FBFBBBFRLR\n" +
                                        "BFBFFFFLLL\n" +
                                        "FFBBFFBLLR\n" +
                                        "FBFFBBFRRR\n" +
                                        "BFFFFFFRLL\n" +
                                        "FBFFFFFLLR\n" +
                                        "FFFBFFBRRL\n" +
                                        "FFBBFBBLRL\n" +
                                        "FBBFBFBLLR\n" +
                                        "BBFFFBFRRL\n" +
                                        "FFBBFBFLRR\n" +
                                        "BFBBFBFLRL\n" +
                                        "FBFBBBFLRL\n" +
                                        "BFFFFFFLRL\n" +
                                        "FFFBFBBRLR\n" +
                                        "FFBBFBBRLR\n" +
                                        "FBBFFBFLLL\n" +
                                        "BFFBFBBLRL\n" +
                                        "FBFFBBBLLL\n" +
                                        "FBBBFFFLRR\n" +
                                        "BFFBBBBLLL\n" +
                                        "FBBBFBFRLL\n" +
                                        "FBBBFBBLRR\n" +
                                        "FBFFFBBRLL\n" +
                                        "FFBFBBBLRR\n" +
                                        "FBFBFFFLRL\n" +
                                        "BFFBFFFRLR\n" +
                                        "FFBBBFBRLR\n" +
                                        "FFFBBFBRLL\n" +
                                        "BFFFFFFLRR\n" +
                                        "FBBBFBBRRR\n" +
                                        "FBFFBFFLRL\n" +
                                        "FBFFBFBLLL\n" +
                                        "FBBBFBFRLR\n" +
                                        "FBFBFBBRLL\n" +
                                        "FBBBFBBLLL\n" +
                                        "FFBBBFBRLL\n" +
                                        "FFFBFBFLLL\n" +
                                        "FBFFFBBRRL\n" +
                                        "BFFFBFFLLL\n" +
                                        "FBBFBFBLRR\n" +
                                        "FBBBBFBLRR\n" +
                                        "FBBFFBFLRR\n" +
                                        "FBBBBBBLRL\n" +
                                        "BFFBFFFRLL\n" +
                                        "BFBFBBFRRL\n" +
                                        "BFBFFFFRRR\n" +
                                        "BFFFBFBRRL\n" +
                                        "FFFFBFBRLL\n" +
                                        "FBFBBFFLRR\n" +
                                        "BBFFFBFLLL\n" +
                                        "BFBBFFBRRR\n" +
                                        "FBBFBFBRRR\n" +
                                        "FBFFBFFRLL\n" +
                                        "BFBFBBBLRR\n" +
                                        "FBBFFBFRRR\n" +
                                        "FBBFBFBRLL\n" +
                                        "BFFFFBBRLR\n" +
                                        "BFBFBBBLLL\n" +
                                        "FBFBFBFLLL\n" +
                                        "BFFBFFBRLR\n" +
                                        "BFBFFFBLLR\n" +
                                        "FFFBFFFRLL\n" +
                                        "FBFFFFFRRR\n" +
                                        "FFFBFFFLRR\n" +
                                        "FFBFFBFRRR\n" +
                                        "BFFFFBFLLL\n" +
                                        "FBBBBFBRRR\n" +
                                        "FBBBFFFLLL\n" +
                                        "FFBFFBBLLR\n" +
                                        "BFFFFFFRRL\n" +
                                        "FFFFBBBLRL\n" +
                                        "FBFBFBBRLR\n" +
                                        "FBBBFFBRLR\n" +
                                        "FBBFBFFRLR\n" +
                                        "BBFFFBFRLR\n" +
                                        "FBBFBBFLLL\n" +
                                        "FBBFFFFLRR\n" +
                                        "FBFFFBBLLL\n" +
                                        "BFBBFFFRLL\n" +
                                        "FFFBFBFRLL\n" +
                                        "BFFFBBFRRR\n" +
                                        "FFBFFBBRRL\n" +
                                        "BBFFFBBLLL\n" +
                                        "BBFFFFFLLR\n" +
                                        "BBFFFFBRLL\n" +
                                        "FBBBFFBRLL\n" +
                                        "FBFBFBFRRL\n" +
                                        "FFFBFBBLLL\n" +
                                        "BFFBFBFLRL\n" +
                                        "BFBFFBBRRR\n" +
                                        "FFFBBBBRRL\n" +
                                        "BFFFBBFLLL\n" +
                                        "FBFFBBBRLL\n" +
                                        "FFFBFBBLRR\n" +
                                        "FBBFFFBLRR\n" +
                                        "BFBBFFFLLR\n" +
                                        "FFBBFFFLRL\n" +
                                        "FBBBFFBRRR\n" +
                                        "FFFBBFFRLR\n" +
                                        "FBFFFFBLLR\n" +
                                        "BFFBFFFRRL\n" +
                                        "FBFBFBFRRR\n" +
                                        "FBBBBBFRLL\n" +
                                        "BFFFFFBRLL\n" +
                                        "FFFBBFBLRL\n" +
                                        "BFFFFFBLLL\n" +
                                        "BFFFBFBLLL\n" +
                                        "FBFBFFFRLR\n" +
                                        "BFBFFFFRLR\n" +
                                        "FBFBBFFRRL\n" +
                                        "BFBBFFFRLR\n" +
                                        "FFBFFFFRLL\n" +
                                        "FFFBBFBRRL\n" +
                                        "FBBBFFBLLL\n" +
                                        "BFBFBFBLRR\n" +
                                        "BFFFFBFRLL\n" +
                                        "BFBBFFBLLL\n" +
                                        "FBBFBBBLLL\n" +
                                        "FBBFBBBRLR\n" +
                                        "BBFFFFBRRL\n" +
                                        "BFBFBFFRRL\n" +
                                        "FBBBFBBRRL\n" +
                                        "BFBBBBFLRR\n" +
                                        "FFBFBBBRRR\n" +
                                        "FFFBFFFLRL\n" +
                                        "FFFBFFFRRR\n" +
                                        "FFBBFBBRRL\n" +
                                        "FFBFBFBLLR\n" +
                                        "BFBFFFBLLL\n" +
                                        "FBFBFFBLLL\n" +
                                        "BFFFBFBLRR\n" +
                                        "BFFBFFBLLL\n" +
                                        "BBFFFFBLRR\n" +
                                        "FFBFBFFRLR\n" +
                                        "FBFFFBFRLR\n" +
                                        "FFBBBBBRLR\n" +
                                        "FBFFFBFRLL\n" +
                                        "FBFBBBBRLL\n" +
                                        "FFBFFFBRRL\n" +
                                        "BFFFBBBLLL\n" +
                                        "FFBBBFBLLL\n" +
                                        "BFFFBFFRRR\n" +
                                        "FFFBBFFRLL\n" +
                                        "FFFBBBFRRL\n" +
                                        "FBFBBFFLRL\n" +
                                        "FFBBFFFLRR\n" +
                                        "FFFFBBBRRL\n" +
                                        "FFBBBBFLLL\n" +
                                        "FFBFFFBRLL\n" +
                                        "FBFFBBBRRL\n" +
                                        "BFBBFFFRRR\n" +
                                        "FFBBBFFLLR\n" +
                                        "FFBBBFFRRL\n" +
                                        "BFBBFBFRLR\n" +
                                        "FFFFBBFLLL\n" +
                                        "FFBBBBFRRL\n" +
                                        "FBBFFFFLLL\n" +
                                        "BFFFBBBRLR\n" +
                                        "FBFFBBBRLR\n" +
                                        "BFBBFFFLRL\n" +
                                        "BFBFBBFLLL\n" +
                                        "FBFFFFBRLR\n" +
                                        "BFFBBFFRRR\n" +
                                        "FBFBBBBLLL\n" +
                                        "BFFBFBBRLL\n" +
                                        "FBFBFFBRLR\n" +
                                        "BFBFBFFLLR\n" +
                                        "FFFFBBFRLL\n" +
                                        "BFFBFFFRRR\n" +
                                        "FBFBBBBRLR\n" +
                                        "BFBBBBFLRL\n" +
                                        "BFBFBFBLLL\n" +
                                        "BFBFFBBLRL\n" +
                                        "BFBFFBBLLR\n" +
                                        "BFBBFFBRLL\n" +
                                        "FFBFBBBLLL\n" +
                                        "BFBFBBBRLL\n" +
                                        "BFBFBBBRRR\n" +
                                        "FFFFBBBLRR\n" +
                                        "FFFBFBFLRR\n" +
                                        "BFFFBBBLLR\n" +
                                        "FBBBBBFLLL\n" +
                                        "FFFBBFBLLL\n" +
                                        "FBFBFFFRLL\n" +
                                        "FBBBFFFRLR\n" +
                                        "FFBFBFFLRR\n" +
                                        "FFFFBBFRLR\n" +
                                        "FFFFBFBRRR\n" +
                                        "FFFBBFBRLR\n" +
                                        "FFBFBFBLLL\n" +
                                        "FFBFFFFLRR\n" +
                                        "FFFBFBFRRR\n" +
                                        "FFBBFFFLLL\n" +
                                        "FBBBFFBLLR\n" +
                                        "BFBFBBBRRL\n" +
                                        "FFBBBFBLRL\n" +
                                        "BFBBBBBRRL\n" +
                                        "FFFBBBBLRR\n" +
                                        "FBBBFFBRRL\n" +
                                        "FFBFBFFRRL\n" +
                                        "FBBBBBBRLR\n" +
                                        "FBFFBFFRRR\n" +
                                        "BFFFFBFRLR\n" +
                                        "FFBBFFBRLL\n" +
                                        "BFFBBBFLLR\n" +
                                        "FBFBFBFRLL\n" +
                                        "BFBFBFBRLR\n" +
                                        "FBFFFBBLLR\n" +
                                        "FBFBFFBRRL\n" +
                                        "FBBFFFBRLL\n" +
                                        "FFBFBFBRLR\n" +
                                        "FFBFBFFRLL\n" +
                                        "FFFBFFBRLR\n" +
                                        "BFBFBFBRRR\n" +
                                        "FFFBBBBRRR\n" +
                                        "BFBFFBFRRR\n" +
                                        "BFBBFFBLRL\n" +
                                        "FBBFFBFRLL\n" +
                                        "BFFBBFFLRL\n" +
                                        "FFBFBFBRLL\n" +
                                        "FBFBBBBLRR\n" +
                                        "BFBFBFBRLL\n" +
                                        "BFBFFBFRRL\n" +
                                        "BFFFFFFRLR\n" +
                                        "FFBFFBBRRR\n" +
                                        "FFBBFBFLLR\n" +
                                        "FFFBBFFLLL\n" +
                                        "BFBBBFBLRL\n" +
                                        "FBFFFFBRLL\n" +
                                        "FBBBFBBRLR\n" +
                                        "BFFFBBFLRR\n" +
                                        "FBBBBFBRLR\n" +
                                        "BFBBBFFLLL\n" +
                                        "FBFBFBBLLL\n" +
                                        "BBFFFFBRLR\n" +
                                        "FBFBFFFLLR\n" +
                                        "FBFBBBBRRL\n" +
                                        "FFBFBBFRRL\n" +
                                        "BFFBBFFLLL\n" +
                                        "FBBFBBFLRR\n" +
                                        "BFFFFFBLLR\n" +
                                        "BFBBFFFLLL\n" +
                                        "FBBFBFFLRR\n" +
                                        "FBBFFBBRRR\n" +
                                        "FBFFFFFLRL\n" +
                                        "BFBFFFBLRR\n" +
                                        "FFFBFFBLRR\n" +
                                        "FBBFFBBRLL\n" +
                                        "BFBBBBBLRL\n" +
                                        "FFFBBBFLRR\n" +
                                        "BFBBBFBLLL\n" +
                                        "FBFFFBBRLR\n" +
                                        "FFBBFBBRLL\n" +
                                        "FBFFFBBLRR\n" +
                                        "FBFBBFFLLR\n" +
                                        "FFFFBBFRRL\n" +
                                        "FBBFFFFRRR\n" +
                                        "BFFBFFFLLR\n" +
                                        "FFFBBFFLRL\n" +
                                        "FFFBBBFLLR\n" +
                                        "BFFFBFFLRL\n" +
                                        "FBBBBFBLLR\n" +
                                        "FFBFBFBLRR\n" +
                                        "BFBBFBFLLL\n" +
                                        "BFFBBFFRLR\n" +
                                        "BFBBBBFLLR\n" +
                                        "FFFFBBFLRR\n" +
                                        "BFBFBBFLRL\n" +
                                        "BBFFFBFLRR\n" +
                                        "BFBBFBBRLR\n" +
                                        "FBFBFFBLRL\n" +
                                        "FFFBBFFLRR\n" +
                                        "FFBBFFFRRR\n" +
                                        "BFFBBBBLLR\n" +
                                        "BBFFFFBLRL\n" +
                                        "FBFFBBFLLL\n" +
                                        "FFFFBBFLLR\n" +
                                        "FBBBFBFRRL\n" +
                                        "FFBFFBBLRL\n" +
                                        "BFBBFFBLLR\n" +
                                        "BFBFFFFLLR\n" +
                                        "BFBBBBBRLR\n" +
                                        "BFBBFBFRLL\n" +
                                        "BFFBFFFLLL\n" +
                                        "FFBFFFFLLL\n" +
                                        "BFBFFBFLLL\n" +
                                        "FBBFFFFLRL\n" +
                                        "BFBBBBBLLR\n" +
                                        "BFFBBFBLRR\n" +
                                        "BFFFBFBLRL\n" +
                                        "FBBBFFFRLL\n" +
                                        "FBBFBFBRRL\n" +
                                        "FBFFFFFRRL";
}
